devops:
- changed-files:
  - any-glob-to-any-file:
    - '.github/workflows/**'
    - '.github/**/*.yml'
    - '.github/**/*.yaml'
    - '**/Dockerfile'
    - '**/Dockerfile.*'

dependencies:
- changed-files:
  - any-glob-to-any-file:
    - Gemfile
    - Gemfile.lock
    - package.json
    - package-lock.json
    - yarn.lock
    - pnpm-lock.yaml

ruby:
- changed-files:
  - any-glob-to-any-file:
    - Gemfile
    - Gemfile.lock
    - '**/*.gemspec'
    - '**/*.rb'

javascript:
- changed-files:
  - any-glob-to-any-file:
    - package.json
    - package-lock.json
    - yarn.lock
    - pnpm-lock.yaml
    - '**/*.js'
    - '**/*.mjs'
    - '**/*.cjs'
    - '**/*.ts'
    - '**/*.tsx'
