# Documentation: https://www.gitpod.io/docs/references/gitpod-yml
image: gitpod/workspace-full

# Task(s)
tasks:
  - before: |
      gem install bundle
      bundle config set --local path 'vendor/bundle'
    init: |
      bundle update
      bundle install
  - name: Run type on strap
    init: bundle install
    command: bundle exec jekyll serve

# In case the user is trying to make a pull request, he needs GitLens, which by default is not installed. This code will help us install it.
vscode:
  extensions:
    - eamodio.gitlens

# Ports configuration, since Gitpod needs to open Type on Strap on a new tab when the server loads up.
ports:
  - port: 4000
    onOpen: open-browser

# For opening workspaces faster than ever, prebuilds are suggested
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: false
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt
