version: 0.1
   
phases:
  install:
    commands:
      - export LANG="en_US.UTF-8"
      - export LC_ALL="en_US.UTF-8"
      - gem install bundler jekyll
  build:
    commands:
      - echo "******** Install Bundles ********"
      - bundle install
      - echo "******** Building Jekyll site ********"
      - bundle exec jekyll build
      - echo "******** Uploading to S3 ********"
      - echo "******** Assets with cache control first ********"
      - aws s3 sync _site/ s3://nutbrown.io --exclude "*" --include "*.css" --include "*.png" --include "*.jpeg" --include "*.js" --include "*.PNG" --cache-control max-age=86400
      - echo "******** Everything Else ********"
      - aws s3 sync --delete _site/ s3://nutbrown.io
      