#!/bin/sh
#
# Called by "git commit" with no arguments.
# The hook should run gulp to optimize assets.
# Will exit with non-zero status if it wants to stop the commit.

: << 'END' # Ancillary code to ensure environment before running gulp
# If it's on the right directory, proceed. Else, try to fix it. If fail, abort commit.
if [ ${PWD##*/} != "lib" ] ; then
    cd lib || exit 1
fi 

# If gulp is intalled and gulpfile.js is present, then proceed. Else, abort commit.
if ! [ -f "gulpfile.js" ] || ! command -v gulp; then  
    printf "gulpfile.js not found or gulp-cli not installed!\n"
    exit 1
fi
END

# Detect if there are assets to optimize and, then, run gulp default task.
if git status --porcelain | grep assets/_ >/dev/null; then
    gulp 
    # Asks if user wants to abort the commit. 
    # FIXME: Git overrides STDIN, this is fundamentally flawed.
    # TODO: Husky may be an alternative, https://github.com/typicode/husky 
    printf "Do you want to abort the commit and stage more files? (Y/n) "
    read -r answer
    case ${answer:0:1} in
        y|Y) exit 1;;
        *) exit 0;;
    esac
fi

# Proceed with the commit.
exit 0

