#!/bin/sh
# OPTIONAL
# Called by "git commit" with no arguments.
# The hook should run npm scripts to optimize assets.
# Will exit with non-zero status if it wants to stop the commit.

: << 'END' # Ancillary code to ensure environment before running npm scripts
# If package.json is present and node is installed, proceed. Else, abort commit.
if ! [ -f "package.json" ] || ! command -v node; then
    printf "package.json not found or node not installed! Run npm install from the project root.\n"
    exit 1
fi
END

# If there are non-staged assets, abort commit.
if git status --porcelain | grep -E '^(\?\?|AM|\nM).*assets/.*$' >/dev/null; then
    printf "There are non-staged assets, be sure to run npm run build before committing changes!\n"
    exit 1
fi

# Proceed with the commit.
exit 0

